### ISSUE TITLE
long first-load time for force views, should still have visible spinner

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#630] opened 2015-07-13 16:11 UTC
there is no spinner so I have no indication if the page will load.

![image](https://cloud.githubusercontent.com/assets/6482926/8654433/3fac0ff6-2958-11e5-8a0e-091740de0c98.png)

any thoughts as to why load times are double compared to looking at the same view in safari?

**Comment by alloy** [comment] 2015-07-14 12:02
I'm unable to reproduce this, all Force views I’m looking at show a spinner during loading. Did you have to perform certain steps to get it into this state?

**Comment by katarinabatina** [comment] 2015-07-14 14:20
I can't either for the time being, let's keep it open for now and put low on the priority list. Will continue to check as the day goes on

**Comment by alloy** [comment] 2015-07-14 16:58
> any thoughts as to why load times are double compared to looking at the same view in safari?

I’m guessing it might be related to Safari having access to the super-duper-optimized JavaScript engine and our current web views in Eigen do not. As Force is pretty JavaScript heavy, this might explain the issue. If this is the case, it will be solved by #606.

**Comment by katarinabatina** [comment] 2015-07-14 17:54
Is 606 making it into this release, or next?

**Comment by alloy** [comment] 2015-07-14 17:54
Next.

**Comment by alloy** [comment] 2015-07-14 17:55
@orta or do you think otherwise?

**Comment by orta** [comment] 2015-07-14 19:23
Next alas

**Comment by orta** [comment] 2015-07-14 19:23
lots of moving parts with that change I'm afraid, don't want it the close to the line

**Comment by alloy** [comment] 2015-07-20 11:37
@katarinabatina I’m gonna close this for now, I think it was a fluke and/or related to the position of the moon and stars :sparkles:

**Closed by alloy** 2015-07-20 11:37 UTC
Labels: iPad, QA, Waiting For Answer
