### ISSUE TITLE
Feedback 'From: Sarah Scott Number of works is NaN'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1928] opened 2016-10-16 09:30 UTC
### Message from 5501de167261696e34610200 sent on 2016-10-16 09:30:18 UTC###

> From: Sarah Scott
> 
> Number of works is NaN

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37020/feedback/640170](https://rink.hockeyapp.net/manage/apps/37020/feedback/640170)

**Comment by sarahscott** [comment] 2016-10-17 12:40
Duplicate of #1625

**Closed by sarahscott** 2016-10-17 12:40 UTC
Labels: bug?, Hockey
