### ISSUE TITLE
Feedback 'From: Remy Ferber Artist name appears cramped a...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1900] opened 2016-10-08 13:53 UTC
### Message from 53c70a737261696fb3010100 sent on 2016-10-08 13:53:11 UTC###

> From: Remy Ferber
> 
> Artist name appears cramped at top of page. Tried closing app and reopening. Favorite artists the tight spacing doesn't appear, but for searched artist (image attached) does appear off.

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/634840](https://rink.hockeyapp.net/manage/apps/37029/feedback/634840)

**Comment by alloy** [comment] 2016-10-10 09:08
@ferberre Thanks for the report!

Closing as a duplicate of #1571

**Closed by alloy** 2016-10-10 09:08 UTC
