### ISSUE TITLE
Fix crash in @objc Artsy.SaleViewModel.closingDate.getter : __ObjC.NSDate, line 50

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2151] opened 2017-02-04 01:53 UTC
### Stacktrace (first of multiple) ###

<pre>-;@objc Artsy.SaleViewModel.closingDate.getter : __ObjC.NSDate;SaleViewModel.swift;50
-;Artsy.AuctionBannerView.((setupViews in _9BECC293EAFD9E95A6AFF46154EBC5BB) (Artsy.AuctionBannerView) -> () -> ()).(closure #2);AuctionBannerView.swift;73
-;Artsy.AuctionBannerView.(setupViews in _9BECC293EAFD9E95A6AFF46154EBC5BB) (Artsy.AuctionBannerView) -> () -> ();AuctionBannerView.swift;79
-;@objc Artsy.AuctionBannerView.traitCollectionDidChange (Artsy.AuctionBannerView) -> (__ObjC.UITraitCollection?) -> ();AuctionBannerView.swift;36
AREmbeddedModelsViewController;setActiveModule:;AREmbeddedModelsViewController.m;125
-;Artsy.AuctionViewController.displayCurrentItems (Artsy.AuctionViewController) -> () -> ();AuctionViewController.swift;208
-;@objc Artsy.AuctionViewController.displayCurrentItems (Artsy.AuctionViewController) -> () -> ();AuctionViewController.swift;0
-;function signature specialization <Arg[0] = Owned To Guaranteed> of Artsy.AuctionViewController.setupForSale (Artsy.AuctionViewController) -> (Artsy.SaleViewModel) -> ();AuctionViewController.swift;165
-;@objc Artsy.AuctionViewController.setupForSale (Artsy.AuctionViewController) -> (Artsy.SaleViewModel) -> ();AuctionViewController.swift;0
-;Artsy.AuctionViewController.(viewWillAppear (Artsy.AuctionViewController) -> (Swift.Bool) -> ()).(closure #1);AuctionViewController.swift;62
-;demangledName(char const*, bool);arclite.mm;1372
-;iRateVersionNumber;;
-;add_image_hook_swiftV1(mach_header const*, long);arclite.mm;323
iRate;resizeAlertView:;iRate.m;989
-;__arclite_objc_readClassPair(objc_class*, objc_image_info const*);arclite.mm;1104
-;iRateVersionNumber;;
-;add_image_hook_swiftV1(mach_header const*, long);arclite.mm;323
iRate;resizeAlertView:;iRate.m;989
-;__arclite_object_getIndexedIvars(objc_object*);arclite.mm;1173
-;iRateVersionNumber;;
-;add_image_hook_swiftV1(mach_header const*, long);arclite.mm;323
iRate;resizeAlertView:;iRate.m;989
-;demangledName(char const*, bool);arclite.mm;1372
-;iRateVersionNumber;;
-;add_image_hook_swiftV1(mach_header const*, long);arclite.mm;323
iRate;resizeAlertView:;iRate.m;989
-;__arclite_objc_readClassPair(objc_class*, objc_image_info const*);arclite.mm;1104
-;Artsy.AuctionSaleArtworksNetworkModel.(fetchSaleArtworks (Artsy.AuctionSaleArtworksNetworkModel) -> (Swift.String, callback : (Interstellar.Result<[__ObjC.SaleArtwork]>) -> ()) -> ()).(closure #1);AuctionSaleArtworksNetworkModel.swift;21
-;Artsy.((fetchPage in _A2CC32B3077A45794C7542EE6485D1A5) (Swift.Int, forSaleID : Swift.String, alreadyFetched : [__ObjC.SaleArtwork], callback : (Interstellar.Result<[__ObjC.SaleArtwork]>) -> ()) -> ()).(closure #1);AuctionSaleArtworksNetworkModel.swift;43</pre>

### Reason ###

Selector name found in current argument registers: endDate

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/155960506](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/155960506)

**Comment by alloy** [comment] 2017-02-07 13:36
Duplicate of #2155.

**Closed by alloy** 2017-02-07 13:36 UTC
