### ISSUE TITLE
Works that have a 'More Info' option on the artwork page have blank 'More Info' pages when you tap through

### ISSUE THREAD

**Issue by celinenguyen** [artsy/eigen#643] opened 2015-07-13 17:56 UTC
For examples, see the Tara Donavan show at the Parrish Art Museum (currently the third item in the featured carousel on the home screen), where 2/3 show items don't have any content when you tap through to the 'More Info' page.

Also, Carsten Höller's *Upside-Down Googles*, 2015 piece (and others from the Höller show at Hayward Gallery at Southbank Centre).

**Comment by alloy** [comment] 2015-07-14 10:57
Duplicate of #130.

**Closed by alloy** 2015-07-14 10:57 UTC
Labels: QA
