### ISSUE TITLE
sometimes nothing loads when app hasn't been opened for a while

### ISSUE THREAD

**Issue by 1aurabrown** [artsy/eigen#374] opened 2015-04-15 19:08 UTC
I've brought this up before and I think it's a legit problem that both Katarina and Robert have reported -- it seems like sometimes when the app opens, all requests fail. There's no feedback or crash, just spinners/missing data. I have no idea how to replicate this. I've seen it happen in the simulator if I select a sim that I haven't used recently. My theory is that some token has reached its expiration date and we aren't handling it correctly. I'm curious if we can add logs to the xapp failure block or someplace similar and have that reported to hockeyapp so that we can get more info on what's actually going on.

**Comment by orta** [comment] 2015-04-15 19:19
It's possible that our non-logged in tokens have an xx day limit, a logged in user would have a20 year token.

**Comment by katarinabatina** [comment] 2015-04-15 22:06
Probably good to note anecdotally we know this to have happened twice to people who just downloaded the app.

**Comment by alloy** [comment] 2015-06-29 15:53
> I'm curious if we can add logs to the xapp failure block or someplace similar and have that reported to hockeyapp so that we can get more info on what's actually going on.

@1aurabrown You _could_ do this now (with `ARLog()`), however, this data will only be submitted to HockeyApp if the application also crashes, which doesn’t seem to be the case.

If you can figure out a code path that would make the application crash (basically assert) when this exceptional case occurs, then maybe that’s a thing to do.

Otherwise I think we should close this one until we get some better feedback on this issue.

**Comment by orta** [comment] 2016-01-11 13:45
I feel like this is a dupe of #979

**Closed by orta** 2016-01-11 13:45 UTC
