### ISSUE TITLE
Related artists are misaligned from the rest of the view

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1567] opened 2016-05-29 13:24 UTC
On the about tab, the margins of the related artists thumbnails are pushed over the left 

![image](https://cloud.githubusercontent.com/assets/6482926/15633593/1df034b8-257f-11e6-9bdb-65a50bef39af.png)

**Comment by alloy** [comment] 2016-05-29 17:32
Aye. Dupe of https://github.com/artsy/emission/issues/131

**Closed by alloy** 2016-05-29 17:32 UTC
Labels: QA
