### ISSUE TITLE
embedded on boarding is tiny and hard to see 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#458] opened 2015-05-20 20:20 UTC
![image](https://cloud.githubusercontent.com/assets/6482926/7735534/db30cdd0-ff0b-11e4-87e8-71f907cb3f41.png)

@1aurabrown I realize this is a force issue but didn't know if there was anything on our end we could do to fix it. 

after embedded onboarding let's not land them in the you tab if possible but instead on the view they came from when they tapped you.

**Comment by 1aurabrown** [comment] 2015-05-20 21:19
I can look at playing around with forcing it to be a certain scale -- the issue is that it's rendering much wider and then scaling down. if we don't scale down, there might be weird side-to-side scrolling due to the white space around the page content. We can check it out.

I think that the embedded onboarding only lands you in the YOU section if you got there as a result of tapping YOU. The ideas is that we complete whatever action it was that you were trying to do before you logged in or signed up.

We could switch this up so that if you tap on you while logged out -> log into you account we then tak you to YOU, but if you made a totally new account we take you to HOME.

**Comment by katarinabatina** [comment] 2015-05-27 17:43
@1aurabrown I like your last idea

**Comment by katarinabatina** [comment] 2015-05-27 17:52
@1aurabrown wrote new issue for the reroute https://github.com/artsy/eigen/issues/481

**Comment by alloy** [comment] 2015-06-29 13:14
If I understand this correctly, this is now fixed as #481 has been fixed by #517.

@katarinabatina Please re-open if this is not the case and I failed to understand an essential part of the issue.

**Closed by alloy** 2015-06-29 13:14 UTC
Labels: ipad
