### ISSUE TITLE
Live UI: Don't publish jump bid if online bidding is ahead

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1683] opened 2016-06-10 18:22 UTC
When operator registered a jump bid from floor we should not print the event in the bid history 

![image](https://cloud.githubusercontent.com/assets/6482926/15974469/96af6b26-2f16-11e6-875e-d07dd29ff266.png)

**Comment by katarinabatina** [comment] 2016-06-10 18:37
this floor bid should appear in the past history, ordered by bid value from highest to lowest. By showing it to the user here its very confusing.

**Comment by devangt** [comment] 2016-06-10 22:31
Really bad but sounds like a dupe of https://github.com/artsy/eigen/issues/1696 ... (which we have kept for now as a Show Stopper)

Lets re-open if we are wrong here.

**Closed by devangt** 2016-06-10 22:31 UTC
Labels: Auctions, SHOW STOPPER
