### ISSUE TITLE
Refresh Auction page when Live Auction goes Live

### ISSUE THREAD

**Issue by devangt** [artsy/eigen#1792] opened 2016-07-19 19:47 UTC
Issue:
When the user is on an auction landing page and it switches to going Live we don't refresh the page so that it prompts the user to enter the live auction or take them directly to the Live. So even if auction is opened we 

![screenshot 2016-07-19 15 48 02](https://cloud.githubusercontent.com/assets/753098/16964231/38a1efa6-4dc8-11e6-86b7-2ebfe3020938.png)

Solution:
We put an explicit CTA on the auction banner "Enter Live Auction" instead of 00:00:00:00

**Comment by ashfurrow** [comment] 2016-07-20 15:00
Is this a dupe of https://github.com/artsy/eigen/issues/1756 ?

**Comment by ashfurrow** [comment] 2016-07-26 15:20
I've done some initial work on this, and there are some questions I think we should answer before we go further. @katarinabatina your input on these would be really helpful.

- When the auction starts, we're just going to show the live interface, right? As if they had just arrived and the live auction was already starting?
- If that's the case, what happens if the user is looking at a lot's artwork page (enter auction view, tap a lot, then the live auction starts). I don't think it makes sense to throw them into the live interface, but wanted to check.
- In the above scenario, when the user taps the back button to return to the auction view, should we present the live interface, even though they arrived at the auction view from the back button?

I think I know the answers to these questions, but I want to verify first.

**Comment by katarinabatina** [comment] 2016-07-27 13:35
1. Yes, just show the live interface
2. What would be best is for any artwork that is in a live auction, when the sale is live, to provide an enter live auction button on the artwork view, similar to what we do on force. 
3. I think when the user taps the back button it makes the most sense to launch the live interface. While it may produce a bit of confusion I wouldn't want someone stuck thinking that the sale hasn't started yet.

**Comment by ashfurrow** [comment] 2016-07-27 14:49
Fantastic, thanks for the succinct and actionable answers 👍

**Closed** 2016-07-28 19:37 UTC
Labels: Auctions, Confirmed Bug
