### ISSUE TITLE
Fix NSInvalidArgumentException in NSAllocateMemoryPages

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2287] opened 2017-04-19 14:16 UTC
### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** NSAllocateMemoryPages(1314624) failed'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/165816270](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/165816270)

**Comment by ashfurrow** [comment] 2017-04-19 15:59
Duplicate of https://github.com/artsy/eigen/issues/2285

**Closed by ashfurrow** 2017-04-19 15:59 UTC
