### ISSUE TITLE
View in room incorrectly scales artwork

### ISSUE THREAD

**Issue by dblock** [artsy/eigen#1298] opened 2016-03-17 23:04 UTC
The work is https://www.artsy.net/artwork/huang-dan-huang-dan-untitled-wu-ti

29 1/2 × 56 7/10 in
75 × 144 cm

![screen shot 2016-03-17 at 7 03 59 pm](https://cloud.githubusercontent.com/assets/542335/13863820/121ef3b2-ec73-11e5-8dbd-e945fcfef637.png)

**Comment by alloy** [comment] 2016-03-22 14:18
Duplicate of #1237.

**Closed by alloy** 2016-03-22 14:18 UTC
