### ISSUE TITLE
Fix NSInternalInconsistencyException in - [ARArtworkPreviewImageView setAspectRatioConstraintWithImage:], line 114

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#526] opened 2015-06-20 00:53 UTC
### Stacktrace (first of multiple) ###

<pre>ARArtworkPreviewImageView;setAspectRatioConstraintWithImage:;ARArtworkPreviewImageView.m;114
ARArtworkPreviewImageView;setImage:;ARArtworkPreviewImageView.m;107
UIImageView(WebCache);sd_setImageWithURL:placeholderImage:options:progress:completed:;UIImageView+WebCache.m;53
UIImageView(WebCache);sd_setImageWithURL:placeholderImage:options:progress:completed:;UIImageView+WebCache.m;53
SDWebImageManager;downloadImageWithURL:options:progress:completed:;SDWebImageManager.m;252
SDImageCache;queryDiskCacheForKey:done:;SDImageCache.m;292
SDWebImageManager;downloadImageWithURL:options:progress:completed:;SDWebImageManager.m;149
UIImageView(WebCache);sd_setImageWithURL:placeholderImage:options:progress:completed:;UIImageView+WebCache.m;51
UIImageView(WebCache);sd_setImageWithURL:placeholderImage:completed:;UIImageView+WebCache.m;34
UIImageView(AsyncImageLoading);ar_setImageWithURL:placeholderImage:completed:;UIImageView+AsyncImageLoading.m;29
UIImageView(AsyncImageLoading);ar_setImageWithURL:placeholderImage:;UIImageView+AsyncImageLoading.m;69
ARArtworkPreviewImageView;updateWithArtwork:;ARArtworkPreviewImageView.m;85
ARArtworkPreviewImageView;setArtwork:;ARArtworkPreviewImageView.m;40
Artwork;onArtworkUpdate:failure:;Artwork.m;296
KSPromise;resolveWithValue:;KSPromise.m;151
KSDeferred;resolveWithValue:;KSDeferred.m;25
Artwork;updateArtwork;Artwork.m;268</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '<NSISEngine: 0x17012b2c0>{ Rows:
	0x1702abb80.posErrorMarker{id: 31425} == 0 + -1*0x17049d1a0.marker{id: 31385} + 1*0x170295bd0.marker{id: 31389} + 1*0x1702abb80.negError{id: 31426} + 1*0x1704ab400.posErrorMarker{id: 31429} + -1*0x1704ab400.negError{id: 31430}
	0x1702b3c80.posErrorMarker{id: 31433} == 0 + 0.00277778*ARWhitespaceGobbler:0x15fd28a30.Height{id: 31420} + 1*0x1702b3c80.negError{id: 31434}
	0x1702bfb00.posErrorMarker{id: 31397} == 0 + 0.00277778*ARWhitespaceGobbler:0x161208430.Height{id: 31292} + 1*0x1702bfb00.negError{id: 31398}
	0x1702bff20.posErrorMarker{id: 31369} == 0 + 1*0x1702bff20.negError{id: 31370} + 0.00277778*ARWhitespaceGobbler:0x161208320.Width{id: 31373}
	0x170497700.posErrorMarker{id: 31313} == 0 + 1*0x170497700.negError{id: 31314} + 0.00277778*ARAuctionBannerView:0x15fdd37d0.Height{id: 31315}
	0x170497bb0.posErrorMarker{id: 31319} == 40 + -0.00277778*ARAuctionBannerView:0x15fdd37d0.Height{id: 31315} + 1*0x170497bb0.negError{id: 31320} + 0.00277778*UILabel:0x15fdab2c0.Height{id: 31321}
	0x1704a17a0.posErrorMarker{id: 31371} == 0 + 0.00277778*ARWhitespaceGobbler:0x161208320.Height{id: 31276} + 1*0x1704a17a0.negError{id: 31372}
	0x1704a2ca0.posErrorMarker{id: 31402} == 0 + 1*0x1704a2ca0.negError{id: 31403} + 0.00277778*ARArtworkRelatedArtworksView:0x15fdb6ee0.Height{id: 31404}
	0x1704a68a0.posErrorMarker{id: 31407} == 0 + 0.00277778*UILabel:0x15fdab2c0.Height{id: 31321} + 1*0x1704a68a0.negError{id: 31408}
	0x1704a69c0.posErrorMarker{id: 31405} == 0 + 1*0x170497750.marker{id: 31316} + -1*0x170494870.marker{id: 31332} + 0.00277778*ARArtworkBlurbView:0x161102d00.Width{id: 31333} + 1*0x17049ccf0.marker{id: 31346} + 1*0x1704a69c0.negError{id: 31406}
	0x1704ad920.posErrorMarker{id: 31431} == 0 + 1*0x1704ad920.negError{id: 31432} + 0.00277778*ARWhitespaceGobbler:0x15fd28a30.Width{id: 31435}
	0x1704b4580.posErrorMarker{id: 31395} == 280 + 1*0x17448fb40.marker{id: 31280} + -1*0x174494eb0.marker{id: 31282} + -1*0x17448dd90.marker{id: 31289} + 1*0x17429ae50.marker{id: 31295} + 1*0x1702b8b40.posErrorMarker{id: 31393} + -1*0x1702b8b40.negError{id: 31394} + 1*0x1704b4580.negError{id: 31396}
	0x1706a6900.posErrorMarker{id: 31399} == 0 + 1*0x1706a6900.negError{id: 31400} + 0.00277778*ARArtworkBlurbView:0x161102d00.Height{id: 31401}
	0x1740b6200.posErrorMarker{id: 31474} == 224.5 + -1*0x174480820.marker{id: 31277} + 1*0x17448fb40.marker{id: 31280} + -1*0x174494eb0.marker{id: 31282} + 1*0x17448e560.marker{id: 31301} + 1*0x1702b8b40.posErrorMarker{id: 31393} + -1*0x1702b8b40.negError{id: 31394} + 1*0x17429a040.marker{id: 31448} + 1*0x1740b6200.negError{id: 31475}
	0x1742a7da0.posErrorMarker{id: 31485} == 23 + 1*0x17429a310.marker{id: 31446} + 1*0x1742a7da0.negError{id: 31486}
	0x1742aa1a0.posErrorMarker{id: 31483} == 140.5 + -1*0x174480820.marker{id: 31277} + 1*0x17448fb40.marker{id: 31280} + -1*0x174494eb0.marker{id: 31282} + 1*0x17448e560.marker{id: 31301} + 1*0x1702b8b40.posErrorMarker{id: 31393} + -1*0x1702b8b40.negError{id: 31394} + 1*0x174492160.marker{id: 31456} + 1*0x1742aa1a0.negError{id: 31484}
	0x1744a1bc0.posErrorMarker{id: 31478} == 84.5 + -1*0x174480820.marker{id: 31277} + 1*0x17448fb40.marker{id: 31280} + -1*0x174494eb0.marker{id: 31282} + 1*0x17448e560.marker{id: 31301} + 1*0x1702b8b40.posErrorMarker{id: 31393} + -1*0x1702b8b40.negError{id: 31394} + 1*0x17448f3c0.marker{id: 31452} + 1*0x1744a1bc0.negError{id: 31479}
	0x1744a1ce0.posErrorMarker{id: 31476} == 28 + 1*0x174294eb0.marker{id: 31444} + 1*0x1744a1ce0.negError{id: 31477}
	ARArtworkActionsView:0x15feeb3e0.Width{id: 31283} == 100800 + 360*0x1702b8b40.posErrorMarker{id: 31393} + -360*0x1702b8b40.negError{id: 31394}
	ARArtworkActionsView:0x15feeb3e0.minX{id: 31281} == 0 + -360*0x174480820.marker{id: 31277} + 360*0x17448fb40.marker{id: 31280} + 180*0x17429a040.marker{id: 31448} + -360*0x174293dd0.marker{id: 31450} + 1*ARSansSerifLabelWithChevron:0x15fddc450'SARKIS'.minX{id: 31451}
	ARArtworkActionsView:0x15feeb3e0.minY{id: 31287} == 0 + -360*0x174485c30.marker{id: 31285} + -1*ARArtworkActionsView:0x15feeb3e0.Height{id: 31288} + 360*0x17448fc30.marker{id: 31291} + -1*ARWhitespaceGobbler:0x161208430.Height{id: 31292} + -360*0x17448eb00.marker{id: 31309} + 1*ARArtworkMetadataView:0x15fed41f0.Height{id: 31310} + 1*ARAuctionBannerView:0x15fdd37d0.Height{id: 31315} + 1*ARAuctionBannerView:0x15fdd37d0.minY{id: 31327} + 360*0x17049c8e0.marker{id: 31410}
	ARArtworkBlurbView:0x161102d00.minX{id: 31337} == 100800 + -360*0x174480820.marker{id: 31277} + 360*0x17448fb40.marker{id: 31280} + -360*0x174494eb0.marker{id: 31282} + -360*0x17448f870.marker{id: 31307} + -180*0x1704986f0.marker{id: 31328} + -360*0x17049a900.marker{id: 31330} + 180*0x170494870.marker{id: 31332} + -1*ARArtworkBlurbView:0x161102d00.Width{id: 31333} + 360*0x17049ab80.marker{id: 31336} + 360*0x1702b8b40.posErrorMarker{id: 31393} + -360*0x1702b8b40.negError{id: 31394} + 180*0x17429a040.mar…

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/37719490](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/37719490)

**Comment by alloy** [comment] 2015-06-24 11:57
These crash logs include information about the artwork being shown:

* Dr. Mohamed Yousif
* Sarkis R5 or R7
* I scream daddio
* Carsten Höller - Multiple Mushroom Dome
* Carsten Höller - Pill Clock
* Irina Nakhova - The Green Pavilion (gas mask)
* Anne Appleby - Jasmine, 2000

Unfortunately none of these have lead me to be able to reproduce the issue.

**Comment by alloy** [comment] 2015-06-24 11:58
Searching for ‘posErrorMarker negerror’ leads to e.g. http://stackoverflow.com/questions/17688370/autolayout-removefromsuperview-removeconstraints-throws-exception-and-crashes which mentions that the order of how constraints are satisfied could be of importance. Unfortunately, without a reproduction I won’t be able to know if any changes make a difference.

**Comment by alloy** [comment] 2015-06-24 12:21
The only change made to this code recently is in this commit https://github.com/artsy/eigen/commit/74f1faac77125db01d7749a929d05d85c3a5f4a6 and is about showing the placeholder image at the right size.

In #479, @1aurabrown mentions this:

> also use the artwork's aspectRatio to make the grey placeholder image if no cached image is available for the artwork (flawed because this number is sometimes incorrect in the json response)

So I wonder what examples of those flawed numbers are, but not sure this is related, because I’d expect numbers not being correct leading to easily reproducible crashes and I have still not been able to reproduce it.

**Comment by alloy** [comment] 2015-06-24 12:21
@orta What’s your thought on pulling the “placeholder image at the right size” code for now and see if that reduces the crashes?

**Comment by alloy** [comment] 2015-06-24 12:23
(That would be an easy change that doesn’t need days of fixing all auto layout issues.)

**Comment by orta** [comment] 2015-06-24 12:29
I don't think that's a good trade off, the app is super ugly on every artwork view without that code.

**Comment by alloy** [comment] 2015-06-24 12:38
@orta I only mean to use this as a way to test if we don’t get anymore crashes. i.e. a way to pinpoint if it is indeed related to this somehow.

**Comment by alloy** [comment] 2015-06-24 12:39
(So removed in the bug fix release and added back afterwards.)

**Comment by orta** [comment] 2015-06-24 12:43
If we're finding it impossible to debug that's fine so long as we don't end up with a full sprint cycle without an update after 2.0.1

**Comment by alloy** [comment] 2015-06-24 12:44
Yeah we’re definitely doing a release at the end of the normal sprint cycle.

**Comment by orta** [comment] 2015-06-24 12:48
:ok:

**Comment by alloy** [comment] 2015-06-25 13:11
Gonna close this for now and see if the error comes back in the 2.0.1 release with the change in #539.

**Comment by orta** [comment] 2015-07-07 08:00
still alive and kicking

**Comment by orta** [comment] 2015-07-07 08:01
ah, but #555 is the new one.

**Closed by orta** 2015-07-07 08:01 UTC
