### ISSUE TITLE
Fix crash in Artsy.LiveAuctionToolbarView.(setupUsingState (Artsy.LotState) -> ()).(closure #1).(closure #1), line 73

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1965] opened 2016-10-22 21:57 UTC
### Stacktrace (first of multiple) ###

<pre>-;Artsy.LiveAuctionToolbarView.(setupUsingState (Artsy.LotState) -> ()).(closure #1).(closure #1);LiveAuctionToolbarView.swift;73
-;Interstellar.Observable.(map <A> ((A) -> A1) -> Interstellar.Observable<A1>).(closure #1);Observable.swift;104
-;partial apply forwarder for Interstellar.Observable.(map <A> ((A) -> A1) -> Interstellar.Observable<A1>).(closure #1);Observable.swift;0
-;Interstellar.Observable.(update (A) -> ()).(closure #1);Observable.swift;59
-;Interstellar.Mutex.lock (() -> ()) -> ();Mutex.swift;39
-;Interstellar.Observable.update (A) -> ();Observable.swift;64
-;function signature specialization <Arg[0] = Owned To Guaranteed> of Artsy.LiveAuctionLotViewModel.addEvents ([__ObjC.LiveEvent]) -> ();LiveAuctionLotViewModel.swift;330
-;Artsy.LiveAuctionLotViewModel.addEvents ([__ObjC.LiveEvent]) -> ();LiveAuctionLotViewModel.swift;313
-;function signature specialization <Arg[0] = Owned To Guaranteed, Arg[1] = Owned To Guaranteed, Arg[2] = Dead and Owned To Guaranteed> of Artsy.LiveAuctionStateReconciler.(updateLotWithEvents in _825FD3FE24083D900CBB43391B945B5D) (Artsy.LiveAuctionLotViewModel, lotEvents : [[Swift.String : Swift.AnyObject]], fullEventOrder : [Swift.String]?) -> ();LiveActionStateReconciler.swift;158
-;function signature specialization <Arg[0] = Owned To Guaranteed> of Artsy.LiveAuctionStateReconciler.processLotEventBroadcast (Swift.AnyObject) -> ();LiveActionStateReconciler.swift;88
-;@objc Artsy.LiveAuctionStateReconciler.processLotEventBroadcast (Swift.AnyObject) -> ();LiveActionStateReconciler.swift;0
-;protocol witness for Artsy.LiveAuctionStateReconcilerType.processLotEventBroadcast (Swift.AnyObject) -> () in conformance Artsy.LiveAuctionStateReconciler : Artsy.LiveAuctionStateReconcilerType in Artsy;LiveActionStateReconciler.swift;77
-;Artsy.LiveAuctionStateManager.(init (host : Swift.String, sale : __ObjC.LiveSale, saleArtworks : [Artsy.LiveAuctionLotViewModel], jwt : Artsy.JWT, bidderCredentials : Artsy.BiddingCredentials, socketCommunicatorCreator : (host : Swift.String, causalitySaleID : Swift.String, jwt : Artsy.JWT) -> Artsy.LiveAuctionSocketCommunicatorType, stateReconcilerCreator : (saleArtworks : [Artsy.LiveAuctionLotViewModel]) -> Artsy.LiveAuctionStateReconcilerType) -> Artsy.LiveAuctionStateManager).(closure #2);LiveAuctionStateManager.swift;58
-;Interstellar.Observable.(update (A) -> ()).(closure #1);Observable.swift;59
-;Interstellar.Mutex.lock (() -> ()) -> ();Mutex.swift;39
-;Interstellar.Observable.update (A) -> ();Observable.swift;64
-;partial apply forwarder for Artsy.LiveAuctionSocketCommunicator.(receivedText in _2FBDEE69475B63219A7CE1A35D4FCE4A) (Swift.String) -> ();LiveAuctionSocketCommunicator.swift;131
-;partial apply forwarder for Artsy.(applyUnowned <A, B, C where A: Swift.AnyObject> (A, (A) -> (B) -> C) -> (B) -> C).(closure #1);SwiftExtensions.swift;13
-;Starscream.WebSocket.((processResponse in _E91840E7069A0D2D302D042308E9D928) (Starscream.WebSocket.WSResponse) -> Swift.Bool).(closure #1);WebSocket.swift;721</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/141706866](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/141706866)

**Comment by ashfurrow** [comment] 2016-10-26 16:28
Dupe of #1969.

**Closed** 2016-10-26 16:28 UTC
