### ISSUE TITLE
Fix NSInvalidArgumentException in - [ARGeneViewController loadGene], line 122

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1408] opened 2016-04-13 01:54 UTC
### Stacktrace ###

<pre>ARGeneViewController;loadGene;ARGeneViewController.m;122
ARGeneViewController;viewDidLoad;ARGeneViewController.m;74</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[Artist updateGene:]: unrecognized selector sent to instance 0x1403600e0'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/115857321](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/115857321)

**Comment by alloy** [comment] 2016-04-13 09:28
Duplicate of #599.

**Closed by alloy** 2016-04-13 09:28 UTC
