### ISSUE TITLE
Feedback 'From: Rachel Goss Text displaying strangely on ...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1992] opened 2016-11-02 23:50 UTC
### Message from 5509b09d7261692ae7c40700 sent on 2016-11-02 23:50:50 UTC###

> From: Rachel Goss
> 
> Text displaying strangely on bottom button

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/651346](https://rink.hockeyapp.net/manage/apps/37029/feedback/651346)

**Comment by alloy** [comment] 2016-11-04 01:53
Duplicate of #1625.

**Closed by alloy** 2016-11-04 01:53 UTC
