### ISSUE TITLE
Fix crash in + [RCTNetworking decodeTextData:fromResponse:], line 344

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2084] opened 2016-12-25 17:38 UTC
### Stacktrace ###

<pre>RCTNetworking;decodeTextData:fromResponse:;RCTNetworking.mm;344
RCTNetworking;sendData:responseType:forTask:;RCTNetworking.mm;367
RCTNetworking;sendRequest:responseType:incrementalUpdates:responseSender:;RCTNetworking.mm;442
RCTNetworkTask;URLRequest:didCompleteWithError:;RCTNetworkTask.m;186
RCTHTTPRequestHandler;URLSession:task:didCompleteWithError:;RCTHTTPRequestHandler.m;114</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/148866462](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/148866462)

**Comment by alloy** [comment] 2017-02-07 13:37
Duplicate of #2153

**Closed by alloy** 2017-02-07 13:37 UTC
