### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by susuyan** [artsy/eigen#2088] opened 2016-12-29 02:53 UTC
Installing Artsy+OSSUIFonts (2.0.2)
Using Artsy+UIColors (3.0.1)
Installing Artsy+UIFonts (1.1.1)

[!] Error installing Artsy+UIFonts
[!] /usr/bin/git clone https://github.com/artsy/Artsy-UIFonts.git /var/folders/rp/mk6x1jqj2336v3klbtdrdfqr0000gn/T/d20161229-66938-1j1kdsj --template= --single-branch --depth 1 --branch 1.1.1

Cloning into '/var/folders/rp/mk6x1jqj2336v3klbtdrdfqr0000gn/T/d20161229-66938-1j1kdsj'...
remote: Repository not found.
fatal: repository 'https://github.com/artsy/Artsy-UIFonts.git/' not found

I found that before the same [issue,](https://github.com/artsy/eigen/issues/1377) but still can not solve the problem.  Thanks!

**Comment by ashfurrow** [comment] 2016-12-29 21:04
Very strange, sorry you're having this issue. If you wouldn't mind providing some more info, it would help us figure out what the problem is. Specifically, when did this issue first begin? Are you using the latest `master` branch of this repo?

**Comment by susuyan** [comment] 2016-12-30 01:58
I was under the **OSS Quick Start** shell operation, the implementation of the **_bundle to the exec pod install_** will appear in this error. Verify that it is the master branch.

**Comment by chresko** [comment] 2016-12-30 05:00
I'm having the exact same problem.

**Comment by chresko** [comment] 2016-12-30 05:03
There's multiple references in the repo to 'https://github.com/artsy/Artsy-UIFonts.git/'.

smackbookpro:eigen chresko$ grep -r "Artsy-UIFonts.git" .
./Pods/Local Podspecs/Artsy+UIFonts.podspec.json:    "git": "https://github.com/artsy/Artsy-UIFonts.git",
./Pods/Manifest.lock:  - Artsy+UIFonts (from `https://github.com/artsy/Artsy-UIFonts.git`)
./Pods/Manifest.lock:    :git: https://github.com/artsy/Artsy-UIFonts.git
./Pods/Manifest.lock:    :git: https://github.com/artsy/Artsy-UIFonts.git
smackbookpro:eigen chresko$

**Comment by chresko** [comment] 2016-12-30 18:16
Is there a workaround until this is fixed? I tried changing the Spec file but that keeps getting updated each time I run bundle exec pod install. Seems like I'd have to fork this into my own repo and make the changes there (unless I'm missing something obvious).

**Comment by chresko** [comment] 2016-12-31 00:15
Okay, after a day of modifying the Podfile, the Podfile.lock file, the Podspec files and the local cocoapods artsy repos, I was able to get this to build. Obviously not a solution, so a PR isn't appropriate. Definitely broken.

**Comment by ashfurrow** [comment] 2016-12-31 15:24
Huh, sorry you're having issues! Can I ask what changes you had to make to get the project to build?

**Comment by chresko** [comment] 2017-01-01 02:54
I removed all instances of [](https://github.com/artsy/Artsy-UIFonts.git) where appropriate, otherwise I replaced [](https://github.com/artsy/Artsy-UIFonts.git) with [](https://github.com/artsy/Artsy-OSSUIFonts).

**Comment by ashfurrow** [comment] 2017-01-02 17:48
Hmm, very tricky! Thanks for getting back to us about that. When you say you replaced the `Artsy-UIFonts` with `Artsy-OSSUIFonts`, do you mean in the eigen Podfile or in the Podfiles for `Artsy-UIButtons` and `Artsy+UILabels`? We recently did a bunch of updates to consolidate how we use fonts and may have missed something, and we really appreciate your help tracking down the problem :bow:

**Comment by chresko** [comment] 2017-01-03 00:03
I'll have to pull the project again and do a diff against all my changes. I'll post them here. There's still a runtime error about not finding a font set - looks like a React message since it's a JavaScript error (selecting ignore allows the app to continue running with what I'm assuming is a default font set).

**Comment by chresko** [comment] 2017-01-11 19:51
I left this alone thinking it would be fixed, but looking at the commit history, looks like no one has take a stab at it?

**Comment by ashfurrow** [comment] 2017-01-11 19:54
Apologies – I was under the impression things were working after a `pod repo update` (based on a different GitHub issue). @susuyan did you get this working without changes to the code? @chresko could you run that diff and post the results here please?

**Comment by chresko** [comment] 2017-01-11 19:56
I'll try a pod repo update and see what happens.

**Comment by chresko** [comment] 2017-01-11 20:46
This is still broken. My diffs aren't going to help because they're local changes and only meant to fix the build issues on my machine. The problem is across multiple repos. You're still using https://github.com/artsy/Artsy-UIFonts.git, which doesn't exist. I'd start by fixing that. Perhaps you could try cloning this yourself as a non-Artsy user?

**Comment by ashfurrow** [comment] 2017-01-11 20:49
Totally, sorry for the issues and thanks for sticking with us. I was hoping you'd provide the diffs as a way to help us figure out what's broken. The UIFonts pod must be being imported as a transitive dependency, and the diff would help us figure out what that is. I'll try cloning.

**Comment by orta** [comment] 2017-01-11 20:51
( in case you're interested in what this repo is: http://artsy.github.io/blog/2014/06/20/artsys-first-closed-source-pod/ )

**Comment by chresko** [comment] 2017-01-11 20:54
I'll need to do something other than a diff since the pod install writes to your .cocoapods directory (which I had to change).

**Comment by chresko** [comment] 2017-01-11 20:58
Okay, I forked and pushed my changes here: https://github.com/chresko/eigen.git

**Comment by ashfurrow** [comment] 2017-01-12 15:36
Thanks, I'll get to it as soon as I can :bow:

**Comment by alloy** [comment] 2017-01-13 19:17
Related https://github.com/artsy/extraction/pull/9

**Comment by jlubeck** [comment] 2017-01-23 16:39
I found this issue as well today. Is there any progress? Anything I can do to help find the issue? Or is that covered already? Are there any workaround until the issue is fixed? Thanks!

**Comment by alloy** [comment] 2017-02-14 15:18
@orta Do you know from the top of your head if this is all good nowadays?

**Comment by alloy** [comment] 2017-02-14 15:19
I guess not #2158.

Closing this in favour of that one to continue the process.

**Closed by alloy** 2017-02-14 15:19 UTC
