### ISSUE TITLE
need minimum password error message

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#632] opened 2015-07-13 17:10 UTC
when singing up and the password is only two characters wrong I can't advance but I am not told why

**Comment by celinenguyen** [comment] 2015-07-13 17:45
Happens on iPhone and iPad. The 'Join' button on the keyboard doesn't do anything but it isn't clear what the error is. The only visual indicator I can see is that the 'Join' text on the upper right only turns white when the password is long enough.

![img_2124](https://cloud.githubusercontent.com/assets/1417844/8656422/6da8c2ca-2965-11e5-98a4-de810cf9eb1e.PNG)


![img_2124](https://cloud.githubusercontent.com/assets/1417844/8656403/53658de4-2965-11e5-88a2-5ecbf2403bfc.PNG)

**Comment by alloy** [comment] 2015-07-13 17:59
Duplicate of #238.

**Closed by alloy** 2015-07-13 17:59 UTC
Labels: QA
