### ISSUE TITLE
Fix RCTFatalException in RCTFatal, line 133

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1619] opened 2016-06-06 05:28 UTC
### Stacktrace ###

<pre>-;RCTFatal;RCTAssert.m;133
RCTExceptionsManager;reportFatalException:stack:exceptionId:;RCTExceptionsManager.m;64
RCTModuleMethod;invokeWithBridge:module:arguments:;RCTModuleMethod.m;489
RCTBatchedBridge;_handleRequestNumber:moduleID:methodID:params:;RCTBatchedBridge.m;968
RCTBatchedBridge;handleBuffer:;RCTBatchedBridge.m;896</pre>

### Reason ###

*** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: undefined is not a function (evaluating 'a.availableTabs().includes(v.WORKS)')', reason: 'Unhandled JS Exception: undefined is not a function (evaluating 'a.availabl..., stack:
t@14:959
mountComponent@293:982
mountComponent@273:162
mountComponent@293:1561
mountComponent@273:162
_updateRenderedComponent@293:4807
_performComponentUpdate@293:4392
updateComponent@293:3669
receiveComponent@293:2948
receiveComponent@273:503
_updateRenderedComponent@293:4623
_performComponentUpdate@293:4392
updateComponent@293:3669
receiveComponent@293:2948
receiveComponent@273:503
_updateRenderedComponent@293:4623
_performComponentUpdate@293:4392
updateComponent@293:3669
performUpdateIfNecessary@293:3190
performUpdateIfNecessary@273:665
r@271:570
perform@276:494
perform@276:494
perform@271:1534
P@271:1706
closeAll@276:1131
perform@276:581
batchedUpdates@270:453
s@271:760
a@290:69
enqueueSetState@290:915
setState@78:317
h@589:1012
<unknown>@525:576
u@34:162
<unknown>@34:916
<unknown>@207:967
callTimer@202:580
callImmediatesPass@202:1249
callImmediates@202:1363
<unknown>@198:2546
k@198:437
value@198:2511
<unknown>@198:1829
k@198:437
value@198:1775
'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/123954504](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/123954504)

**Comment by alloy** [comment] 2016-06-10 22:17
This one I have been unable to reproduce. I wonder if the issue has to do with us depending on the object being fully usable in the constructor, so I’m moving this logic out of there and we’ll see.

**Closed** 2016-06-13 10:58 UTC
