### ISSUE TITLE
Fix NSInvalidArgumentException in + [ARRouter newCreateUserViaFacebookRequestWithToken:email:name:], line 344

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2068] opened 2016-12-07 22:06 UTC
### Stacktrace (first of multiple) ###

<pre>ARRouter;newCreateUserViaFacebookRequestWithToken:email:name:;ARRouter.m;344
ARUserManager;createUserViaFacebookWithToken:email:name:success:failure:;ARUserManager.m;420
ArtsyAPI;getXappTokenWithCompletion:failure:;ArtsyAPI.m;164
ArtsyAPI;getXappTokenWithCompletion:failure:;ArtsyAPI.m;95
ARUserManager;createUserViaFacebookWithToken:email:name:success:failure:;ARUserManager.m;419
ARCreateAccountViewController;fbSuccessWithToken:email:name:;ARCreateAccountViewController.m;394
ARCreateAccountViewController;fb:;ARCreateAccountViewController.m;377
ARAuthProviders;getTokenForFacebook:failure:;ARAuthProviders.m;67</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/148134339](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/148134339)

**Comment by alloy** [comment] 2017-02-07 13:48
Duplicate of #2135.

**Closed by alloy** 2017-02-07 13:48 UTC
