### ISSUE TITLE
no network despite having fine connection

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#915] opened 2015-10-28 21:43 UTC
Issue I've talked about before, opened previous beta, update to 2.3.1, still get a screen that looks like this 
![image](https://cloud.githubusercontent.com/assets/6482926/10803957/407430b6-7d9b-11e5-8650-829224b2970a.png)

I've seen this happen in production as well, have had people run their phones to me showing me the issue. The only way I know how to fix it is deleting the app 0.0. Can't remember if we're capturing the story anywhere else but thought I would surface it here.

**Comment by alloy** [comment] 2015-10-29 09:28
I’ll have to come up with a way for me to remotely debug this (i.e. how to ask you for information).

**Comment by orta** [comment] 2015-10-29 09:28
I wondered about this last night, what if it is an expired XAPP token that we're not re-requesting correctly?

**Comment by alloy** [comment] 2015-10-29 09:31
Yeah something like that would be my guess as well. So this needs some well crafted logging added so that we can get that from e.g. @katarinabatina’s device.

**Comment by orta** [comment] 2015-10-29 09:32
If it's still installed on the device, I can grab the logs from her phone when I'm in the office?

But I feel a manual code review ( or setting your token timeout to be 5m in code ) might catch something.

**Comment by orta** [comment] 2016-01-11 13:30
Dupe of #979

**Closed by orta** 2016-01-11 13:30 UTC
