### ISSUE TITLE
Live: iPad data stale

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1694] opened 2016-06-10 21:07 UTC
Not getting the current state of the auction on iPad

Show all live auctions, click on sale, get this
![img_0372](https://cloud.githubusercontent.com/assets/6482926/15978677/c15af6bc-2f2d-11e6-9325-211841677fd4.PNG)

**Comment by katarinabatina** [comment] 2016-06-10 21:08
working ok on iphone

**Comment by ashfurrow** [comment] 2016-06-10 21:37
This is due to no connection to causality. Not sure what woods cause that.

**Comment by devangt** [comment] 2016-06-10 22:23
Craig and I are triaging and this gets mitigated by user starting the app again. We will continue to triage causality connections next week and if we find a root cause fix. 

Removing - showstopper

**Comment by katarinabatina** [comment] 2016-06-15 02:58
@devangt @ashfurrow we hit this again today. We won't be able to rely on users restarting their apps is there another solution can think of? Maybe we the loading state for getting metaphysics/causality data will take care of it???

**Comment by ashfurrow** [comment] 2016-06-15 12:03
Can you describe in detail how you landed here? Was it working then stopped? When you exited the live interface and returned, did it work? When you restarted the app?

**Comment by acjay** [comment] 2016-06-15 17:27
From what I can tell, this is also an instance of showing the UI before the Causality data arrives. Closing as dupe of #1633, but fell free to reopen if I'm wrong.

**Closed by acjay** 2016-06-15 17:27 UTC
Labels: Auctions
