### ISSUE TITLE
top margin is running into status bar on login 

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#120] opened 2015-02-06 21:14 UTC
![image](https://cloud.githubusercontent.com/assets/6482926/6087568/32a2bcf0-ae1b-11e4-8e17-97b44341b991.png)

**Comment by ashfurrow** [comment] 2015-03-24 18:56
This looks like a duplicate of #26 which was fixed in #181 – Katarina, please re-open if this is incorrect.

**Closed by ashfurrow** 2015-03-24 18:56 UTC
Labels: confirmed bug, iOS8
