### ISSUE TITLE
Feedback 'From: Owen Dodd Weird top spacing on artist pages'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1789] opened 2016-07-18 20:09 UTC
### Message from 54a9d9667261691d4c191200 sent on 2016-07-18 20:09:21 UTC###

> From: Owen Dodd
> 
> Weird top spacing on artist pages

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/587233](https://rink.hockeyapp.net/manage/apps/37029/feedback/587233)

**Comment by alloy** [comment] 2016-07-19 09:32
Duplicate of #1571.

**Closed by alloy** 2016-07-19 09:32 UTC
