### ISSUE TITLE
Feedback 'From: orta@artsymail.com Fair artist pages are ...'

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#1986] opened 2016-11-01 19:32 UTC
### Message from 4ec92ccb56ae88000100038e sent on 2016-11-01 19:32:00 UTC###

> From: orta@artsymail.com
> 
> Fair artist pages are a bit naff on the old nab buttons

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/feedback/650479](https://rink.hockeyapp.net/manage/apps/37029/feedback/650479)

**Comment by alloy** [comment] 2016-11-04 02:05
Duplicate of #1625

**Closed by alloy** 2016-11-04 02:05 UTC
