### ISSUE TITLE
Fix crash in - [HockeyAppProvider event:withProperties:], line 90

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2098] opened 2017-01-07 03:42 UTC
### Stacktrace ###

<pre>HockeyAppProvider;event:withProperties:;HockeyAppProvider.m;90
ARAnalytics;iterateThroughProviders:;ARAnalytics.m;734
ARAnalytics;event:withProperties:;ARAnalytics.m;602
ARAnalytics(DSL);addEventAnalyticsHook:;ARDSL.m;82
RACSubscriber;sendNext:;RACSubscriber.m;73
RACPassthroughSubscriber;sendNext:;RACPassthroughSubscriber.m;74
RACSubject;enumerateSubscribersUsingBlock:;RACSubject.m;85
RACSubject;sendNext:;RACSubject.m;92
-;__RACSwizzleForwardInvocation_block_invoke;NSObject+RACSelectorSignal.m;54
ARArtworkSetViewController;viewDidLoad;ARArtworkSetViewController.m;80</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/152240594](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/152240594)

**Comment by alloy** [comment] 2017-02-07 13:37
Duplicate of #2154

**Closed by alloy** 2017-02-07 13:37 UTC
