### ISSUE TITLE
Tapping search results does not work

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#2022] opened 2016-11-17 22:24 UTC
tap search, search term, tap result, VC closes but nothing happens.

**Comment by sarahscott** [comment] 2016-11-18 13:20
Seems to be a problem for Artists and Shows but Genes, Partners, and Artworks will load if tapped. It doesn't seem to matter if the view is RN or not.

**Comment by alloy** [comment] 2016-11-18 21:19
The problem is _just_ shows.

It seems that since shows got added to the `/api/v1/match` endpoint, we are now:
* No longer getting back artists in many cases (with the default endpoint params).
* Many shows have just the name of the artists, which makes it _seem_ as if a search result represents an artist.
* Our search VC does not filter out shows because it previously expected that to be returned in fair searches _only_, however the app-wide search controller does not expect show results and simply ignores them.

----

So, given a search query like ‘andy warhol’, these are the results:

```json
[
  {
    "model": "partnershow",
    "_id": "57eedfedb202a323b40001b4",
    "id": "hohmann-andy-warhol",
    "display": "Andy Warhol",
    "label": "Partnershow",
    "image_url": "https://d32dm0rphc51dk.cloudfront.net/LFxhqcTnhT1f_cRi2TOftQ/square.jpg",
    "published": true,
    "start_at": "2016-09-30T12:00:00.000Z",
    "end_at": "2016-10-30T12:00:00.000Z",
    "published_at": "",
    "city": "Palm Desert",
    "address": "73-660 El Paseo",
    "venue": "HOHMANN",
    "description": "",
    "artist_names": [
      "Andy Warhol"
    ],
    "search_detail": "",
    "highlights": ""
  },
  {
    "model": "partnershow",
    "_id": "525fed58c9dc24618c000024",
    "id": "the-brant-foundation-andy-warhol",
    "display": "Andy Warhol",
    "label": "Partnershow",
    "image_url": "https://d32dm0rphc51dk.cloudfront.net/QxtsOTOXAdeJINf2PbQTPg/square.jpg",
    "published": true,
    "start_at": "2013-05-12T04:00:00.000Z",
    "end_at": "2013-10-01T04:00:00.000Z",
    "published_at": "",
    "city": "",
    "address": "",
    "venue": "Brant Foundation",
    "description": "",
    "artist_names": [
      "Andy Warhol"
    ],
    "search_detail": "",
    "highlights": ""
  },
  {
    "model": "partnershow",
    "_id": "570e7a217622dd6585000712",
    "id": "guy-hepner-andy-warhol-the-last-decade",
    "display": "Andy Warhol: The Last Decade",
    "label": "Partnershow",
    "image_url": "https://d32dm0rphc51dk.cloudfront.net/24G0geUiHREZKtR9O2k-Qw/square.jpg",
    "published": true,
    "start_at": "2016-04-11T12:00:00.000Z",
    "end_at": "2016-04-22T12:00:00.000Z",
    "published_at": "",
    "city": "New York",
    "address": "568 Broadway ",
    "venue": "Guy Hepner",
    "description": "",
    "artist_names": [
      "Andy Warhol"
    ],
    "search_detail": "",
    "highlights": ""
  },
  {
    "model": "partnershow",
    "_id": "5644d88b2a893a30b100001a",
    "id": "revolver-gallery-andy-warhol-revisited-part-ii",
    "display": "Andy Warhol Revisited Part II",
    "label": "Partnershow",
    "image_url": "https://d32dm0rphc51dk.cloudfront.net/NY2NVTQ5xro-65_Ct8_rFw/square.jpg",
    "published": true,
    "start_at": "2015-11-03T12:00:00.000Z",
    "end_at": "2015-12-30T12:00:00.000Z",
    "published_at": "",
    "city": "Toronto",
    "address": "77 Bloor St W",
    "venue": "Revolver Gallery",
    "description": "",
    "artist_names": [
      "Andy Warhol"
    ],
    "search_detail": "",
    "highlights": ""
  },
  {
    "model": "partnershow",
    "_id": "559c516172616922bc000579",
    "id": "revolver-gallery-andy-warhol-revisited",
    "display": "Andy Warhol: Revisited",
    "label": "Partnershow",
    "image_url": "https://d32dm0rphc51dk.cloudfront.net/HMJ09ezKuAGlwLMBb7M1cQ/square.jpg",
    "published": true,
    "start_at": "2015-07-01T12:00:00.000Z",
    "end_at": "2015-12-31T12:00:00.000Z",
    "published_at": "",
    "city": "",
    "address": "",
    "venue": "Revolver Gallery",
    "description": "",
    "artist_names": [
      "Andy Warhol"
    ],
    "search_detail": "",
    "highlights": ""
  }
]
```

Which renders a search results overview like:

![img_9441](https://cloud.githubusercontent.com/assets/2320/20447035/b00edd14-adaa-11e6-911f-299c41e417c6.PNG)

The first two entries look like they might be the artist, however they both are shows and tapping them does nothing but dismiss the search view.

**Comment by alloy** [comment] 2016-11-18 23:49
Should be fixed once https://github.com/artsy/gravity/pull/10582#issuecomment-261671893 is deployed.

**Comment by alloy** [comment] 2016-11-19 19:45
This is now deployed.

**Closed by alloy** 2016-11-19 19:45 UTC
