### ISSUE TITLE
Fix crash in - [RCTShadowText buildTextStorageForWidth:widthMode:], line 211

### ISSUE THREAD

**Issue by artsyit** [artsy/eigen#2180] opened 2017-02-16 10:28 UTC
### Stacktrace (first of multiple) ###

<pre>RCTShadowText;buildTextStorageForWidth:widthMode:;RCTShadowText.m;211
RCTShadowText;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowText.m;153
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowText;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowText.m;144
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTShadowView;applyLayoutToChildren:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;180
RCTShadowView;applyLayoutNode:viewsWithNewFrame:absolutePosition:;RCTShadowView.m;171
RCTRootShadowView;collectViewsWithUpdatedFrames;RCTRootShadowView.m;55
RCTUIManager;uiBlockWithLayoutUpdateForRootView:;RCTUIManager.m;531
RCTUIManager;_layoutAndMount;RCTUIManager.m;1127
RCTBatchedBridge;batchDidComplete;RCTBatchedBridge.m;1008</pre>

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/157216095](https://rink.hockeyapp.net/manage/apps/37029/crash_reasons/157216095)

**Comment by alloy** [comment] 2017-02-21 12:11
Duplicate of #2001

**Closed by alloy** 2017-02-21 12:11 UTC
