### ISSUE TITLE
Error when trying to place a bid on an online only lot in staging

### ISSUE THREAD

**Issue by katarinabatina** [artsy/eigen#1655] opened 2016-06-08 19:42 UTC
![image](https://cloud.githubusercontent.com/assets/6482926/15908405/8b55ca78-2d8f-11e6-9547-970fd0c77b66.png)

**Comment by orta** [comment] 2016-06-08 20:29
You want to make sure this is in force too, it's their bug 👍

**Comment by devangt** [comment] 2016-06-08 23:38
dupe of https://github.com/artsy/force/issues/5175

**Closed by devangt** 2016-06-08 23:38 UTC
Labels: Auctions, P0
